allOf:
  - $ref: './EntityMeta.yaml'
  - type: object
    properties:
      title: { type: string }
      description: { type: string }
      config: { $ref: './WorkspaceConfig.yaml' }
    required: [config]
