type: object
properties:
  items:
    type: array
    items: { $ref: './WorkspaceConfiguration.yaml' }
  page: { type: integer }
  perPage: { type: integer }
  total: { type: integer }
required: [items, page, perPage, total]
