type: object
properties:
  image: { type: string }
  env:
    type: array
    items: { $ref: './WorkspaceEnvItem.yaml' }
  initialScript: { type: string }
  cpu_limit:
    oneOf:
      - { type: number }
      - { type: string }
  memory_limit:
    oneOf:
      - { type: number }
      - { type: string }
  platform: { $ref: './WorkspacePlatform.yaml' }
  enableDinD: { type: boolean, default: false }
  ttlSeconds: { type: integer, minimum: 0, default: 86400 }
  nix: { type: object }
  volumes: { $ref: './WorkspaceVolumeConfig.yaml' }
additionalProperties: false
